name: 'Email Release Notes'
description: 'Email Release Notes to @Brafton distribution list'
inputs:
  github_token:
    description: A Github token for the repo, usually `{{ github.token }}`.
    required: true
  repo_name:
    description: The repo name that we're working on.
    required: true
  product_name:
    description: The optional different name for the product to appear in posts
    required: false
  email_recipient:
    description: The email address to send to
    required: true
  email_username:
    description: Username for the dedicated gmail sender user
    required: true
  email_password:
    description: Password for the dedicated gmail sender user
    required: true
  email_sender:
    description: Sender email address
    required: true
  host_name: 
    description: SMTP host name
    required: true
  send_secure: 
    description: Use HTTPS or not to connect to the host
    default: false
runs:
  using: 'node12'
  main: 'index.js'
